import { VocabularyItem } from '../types';

const initialVocabulary: VocabularyItem[] = [
  // --- ESSENTIAL BASICS (20) ---
  { id: '1', latvian: 'Sveiki', dutch: 'Hallo' },
  { id: '2', latvian: 'Paldies', dutch: 'Dank je' },
  { id: '3', latvian: 'Lūdzu', dutch: 'Alsjeblieft' },
  { id: '4', latvian: 'Jā', dutch: 'Ja' },
  { id: '5', latvian: 'Nē', dutch: 'Nee' },
  { id: '6', latvian: 'Es', dutch: 'Ik' },
  { id: '7', latvian: 'Tu', dutch: 'Jij' },
  { id: '8', latvian: 'Viņš', dutch: 'Hij' },
  { id: '9', latvian: 'Viņa', dutch: 'Zij' },
  { id: '10', latvian: 'Mēs', dutch: 'Wij' },
  { id: '11', latvian: 'Labrīt', dutch: 'Goedemorgen' },
  { id: '12', latvian: 'Labdien', dutch: 'Goedemiddag' },
  { id: '13', latvian: 'Labvakar', dutch: 'Goedenavond' },
  { id: '14', latvian: 'Ar labunakti', dutch: 'Welterusten' },
  { id: '15', latvian: 'Uz redzēšanos', dutch: 'Tot ziens' },
  { id: '16', latvian: 'Kā iet?', dutch: 'Hoe gaat het?' },
  { id: '17', latvian: 'Labi', dutch: 'Goed' },
  { id: '18', latvian: 'Slikti', dutch: 'Slecht' },
  { id: '19', latvian: 'Atvainojiet', dutch: 'Pardon' },
  { id: '20', latvian: 'Nekas', dutch: 'Geen probleem' },

  // --- SENTENCES: INTRODUCTIONS (10) ---
  { id: '21', latvian: 'Kā tevi sauc?', dutch: 'Hoe heet je?', isSentence: true },
  { id: '22', latvian: 'Mani sauc Anna.', dutch: 'Ik heet Anna.', isSentence: true },
  { id: '23', latvian: 'Prieks iepazīties.', dutch: 'Leuk je te ontmoeten.', isSentence: true },
  { id: '24', latvian: 'No kurienes tu esi?', dutch: 'Waar kom je vandaan?', isSentence: true },
  { id: '25', latvian: 'Es esmu no Latvijas.', dutch: 'Ik kom uit Letland.', isSentence: true },
  { id: '26', latvian: 'Es esmu no Nīderlandes.', dutch: 'Ik kom uit Nederland.', isSentence: true },
  { id: '27', latvian: 'Kur tu dzīvo?', dutch: 'Waar woon je?', isSentence: true },
  { id: '28', latvian: 'Es dzīvoju Rīgā.', dutch: 'Ik woon in Riga.', isSentence: true },
  { id: '29', latvian: 'Cik tev ir gadu?', dutch: 'Hoe oud ben je?', isSentence: true },
  { id: '30', latvian: 'Es runāju nedaudz holandiešu valodā.', dutch: 'Ik spreek een beetje Nederlands.', isSentence: true },

  // --- SENTENCES: COMMUNICATION PROBLEMS (10) ---
  { id: '31', latvian: 'Vai jūs runājat angliski?', dutch: 'Spreekt u Engels?', isSentence: true },
  { id: '32', latvian: 'Es nesaprotu.', dutch: 'Ik begrijp het niet.', isSentence: true },
  { id: '33', latvian: 'Es nezinu.', dutch: 'Ik weet het niet.', isSentence: true },
  { id: '34', latvian: 'Lūdzu, runājiet lēnāk.', dutch: 'Spreek langzamer alstublieft.', isSentence: true },
  { id: '35', latvian: 'Ko tas nozīmē?', dutch: 'Wat betekent dat?', isSentence: true },
  { id: '36', latvian: 'Vai varat to atkārtot?', dutch: 'Kunt u dat herhalen?', isSentence: true },
  { id: '37', latvian: 'Lūdzu, uzrakstiet to.', dutch: 'Schrijf het alstublieft op.', isSentence: true },
  { id: '38', latvian: 'Kā to pasaka holandiski?', dutch: 'Hoe zeg je dat in het Nederlands?', isSentence: true },
  { id: '39', latvian: 'Man ir jautājums.', dutch: 'Ik heb een vraag.', isSentence: true },
  { id: '40', latvian: 'Es mācos valodu.', dutch: 'Ik leer de taal.', isSentence: true },

  // --- SENTENCES: TRAVEL & DIRECTIONS (15) ---
  { id: '41', latvian: 'Kur ir tualete?', dutch: 'Waar is het toilet?', isSentence: true },
  { id: '42', latvian: 'Es meklēju staciju.', dutch: 'Ik zoek het station.', isSentence: true },
  { id: '43', latvian: 'Kur ir lidosta?', dutch: 'Waar is de luchthaven?', isSentence: true },
  { id: '44', latvian: 'Cik maksā biļete?', dutch: 'Hoeveel kost een kaartje?', isSentence: true },
  { id: '45', latvian: 'Kad atiet vilciens?', dutch: 'Wanneer vertrekt de trein?', isSentence: true },
  { id: '46', latvian: 'Kur ir viesnīca?', dutch: 'Waar is het hotel?', isSentence: true },
  { id: '47', latvian: 'Pa labi.', dutch: 'Naar rechts.', isSentence: true },
  { id: '48', latvian: 'Pa kreisi.', dutch: 'Naar links.', isSentence: true },
  { id: '49', latvian: 'Taisni uz priekšu.', dutch: 'Rechtdoor.', isSentence: true },
  { id: '50', latvian: 'Vai tas ir tālu?', dutch: 'Is het ver?', isSentence: true },
  { id: '51', latvian: 'Pestājiet šeit, lūdzu.', dutch: 'Stop hier, alstublieft.', isSentence: true },
  { id: '52', latvian: 'Es esmu apmaldījies.', dutch: 'Ik ben de weg kwijt.', isSentence: true },
  { id: '53', latvian: 'Vai jūs varat man palīdzēt?', dutch: 'Kunt u mij helpen?', isSentence: true },
  { id: '54', latvian: 'Kur es varu nopirkt biļeti?', dutch: 'Waar kan ik een kaartje kopen?', isSentence: true },
  { id: '55', latvian: 'Uz centru, lūdzu.', dutch: 'Naar het centrum, alstublieft.', isSentence: true },

  // --- SENTENCES: RESTAURANT & FOOD (15) ---
  { id: '56', latvian: 'Es gribētu galdiņu diviem.', dutch: 'Ik wil graag een tafel voor twee.', isSentence: true },
  { id: '57', latvian: 'Vai es varu redzēt ēdienkarti?', dutch: 'Mag ik de menukaart zien?', isSentence: true },
  { id: '58', latvian: 'Es esmu veģetārietis.', dutch: 'Ik ben vegetariër.', isSentence: true },
  { id: '59', latvian: 'Es gribētu ūdeni.', dutch: 'Ik wil graag water.', isSentence: true },
  { id: '60', latvian: 'Vienu alu, lūdzu.', dutch: 'Een bier, alstublieft.', isSentence: true },
  { id: '61', latvian: 'Rēķinu, lūdzu.', dutch: 'De rekening, alstublieft.', isSentence: true },
  { id: '62', latvian: 'Tas bija ļoti garšīgi.', dutch: 'Dat was erg lekker.', isSentence: true },
  { id: '63', latvian: 'Labu apetīti.', dutch: 'Eet smakelijk.', isSentence: true },
  { id: '64', latvian: 'Es gribētu kafiju.', dutch: 'Ik wil graag koffie.', isSentence: true },
  { id: '65', latvian: 'Vai jums ir brokastis?', dutch: 'Heeft u ontbijt?', isSentence: true },
  { id: '66', latvian: 'Es neēdu gaļu.', dutch: 'Ik eet geen vlees.', isSentence: true },
  { id: '67', latvian: 'Cik tas maksā?', dutch: 'Hoeveel kost dat?', isSentence: true },
  { id: '68', latvian: 'Vai varu maksāt ar karti?', dutch: 'Kan ik met kaart betalen?', isSentence: true },
  { id: '69', latvian: 'Mēs gribētu pasūtīt.', dutch: 'Wij willen graag bestellen.', isSentence: true },
  { id: '70', latvian: 'Uz veselību!', dutch: 'Proost!', isSentence: true },

  // --- SENTENCES: SHOPPING (10) ---
  { id: '71', latvian: 'Cikos veikals atveras?', dutch: 'Hoe laat gaat de winkel open?', isSentence: true },
  { id: '72', latvian: 'Cikos veikals slēdzas?', dutch: 'Hoe laat sluit de winkel?', isSentence: true },
  { id: '73', latvian: 'Es tikai skatos.', dutch: 'Ik ben alleen aan het kijken.', isSentence: true },
  { id: '74', latvian: 'Vai jums ir šis citā krāsā?', dutch: 'Heeft u dit in een andere kleur?', isSentence: true },
  { id: '75', latvian: 'Tas ir pārāk dārgs.', dutch: 'Dat is te duur.', isSentence: true },
  { id: '76', latvian: 'Es to ņemšu.', dutch: 'Ik neem het.', isSentence: true },
  { id: '77', latvian: 'Vai varu to pielaikot?', dutch: 'Kan ik dit passen?', isSentence: true },
  { id: '78', latvian: 'Kur ir ģērbtuve?', dutch: 'Waar is de paskamer?', isSentence: true },
  { id: '79', latvian: 'Vai jums ir maisiņš?', dutch: 'Heeft u een tasje?', isSentence: true },
  { id: '80', latvian: 'Izpārdošana.', dutch: 'Uitverkoop.', isSentence: true },

  // --- SENTENCES: EMERGENCIES (10) ---
  { id: '81', latvian: 'Palīgā!', dutch: 'Help!', isSentence: true },
  { id: '82', latvian: 'Izsauciet policiju!', dutch: 'Bel de politie!', isSentence: true },
  { id: '83', latvian: 'Man vajag ārstu.', dutch: 'Ik heb een dokter nodig.', isSentence: true },
  { id: '84', latvian: 'Man sāp.', dutch: 'Ik heb pijn.', isSentence: true },
  { id: '85', latvian: 'Es pazaudēju savu pasi.', dutch: 'Ik ben mijn paspoort kwijt.', isSentence: true },
  { id: '86', latvian: 'Es pazaudēju savu telefonu.', dutch: 'Ik ben mijn telefoon kwijt.', isSentence: true },
  { id: '87', latvian: 'Uzmanību!', dutch: 'Pas op!', isSentence: true },
  { id: '88', latvian: 'Ugunsgrēks!', dutch: 'Brand!', isSentence: true },
  { id: '89', latvian: 'Apstājieties!', dutch: 'Stop!', isSentence: true },
  { id: '90', latvian: 'Kur ir slimnīca?', dutch: 'Waar is het ziekenhuis?', isSentence: true },

  // --- SENTENCES: FEELINGS & OPINIONS (15) ---
  { id: '91', latvian: 'Es esmu noguris.', dutch: 'Ik ben moe.', isSentence: true },
  { id: '92', latvian: 'Es esmu laimīgs.', dutch: 'Ik ben gelukkig.', isSentence: true },
  { id: '93', latvian: 'Man ir garlaicīgi.', dutch: 'Ik verveel me.', isSentence: true },
  { id: '94', latvian: 'Man ir auksti.', dutch: 'Ik heb het koud.', isSentence: true },
  { id: '95', latvian: 'Man ir karsti.', dutch: 'Ik heb het warm.', isSentence: true },
  { id: '96', latvian: 'Es esmu izsalcis.', dutch: 'Ik heb honger.', isSentence: true },
  { id: '97', latvian: 'Es esmu izslāpis.', dutch: 'Ik heb dorst.', isSentence: true },
  { id: '98', latvian: 'Man tas patīk.', dutch: 'Ik vind het leuk.', isSentence: true },
  { id: '99', latvian: 'Man tas nepatīk.', dutch: 'Ik vind het niet leuk.', isSentence: true },
  { id: '100', latvian: 'Es tevi mīlu.', dutch: 'Ik hou van jou.', isSentence: true },
  { id: '101', latvian: 'Tas ir interesanti.', dutch: 'Dat is interessant.', isSentence: true },
  { id: '102', latvian: 'Tas ir smieklīgi.', dutch: 'Dat is grappig.', isSentence: true },
  { id: '103', latvian: 'Man ir bail.', dutch: 'Ik ben bang.', isSentence: true },
  { id: '104', latvian: 'Esmu pārsteigts.', dutch: 'Ik ben verbaasd.', isSentence: true },
  { id: '105', latvian: 'Es piekrītu.', dutch: 'Ik ben het ermee eens.', isSentence: true },

  // --- SENTENCES: TIME & WEATHER (15) ---
  { id: '106', latvian: 'Cik ir pulkstenis?', dutch: 'Hoe laat is het?', isSentence: true },
  { id: '107', latvian: 'Ir pulkstenis pieci.', dutch: 'Het is vijf uur.', isSentence: true },
  { id: '108', latvian: 'Šodien ir silts.', dutch: 'Het is warm vandaag.', isSentence: true },
  { id: '109', latvian: 'Lietus līst.', dutch: 'Het regent.', isSentence: true },
  { id: '110', latvian: 'Spīd saule.', dutch: 'De zon schijnt.', isSentence: true },
  { id: '111', latvian: 'Snieg sniegs.', dutch: 'Het sneeuwt.', isSentence: true },
  { id: '112', latvian: 'Ir vējains.', dutch: 'Het waait.', isSentence: true },
  { id: '113', latvian: 'Kāds šodien ir datums?', dutch: 'Welke datum is het vandaag?', isSentence: true },
  { id: '114', latvian: 'Daudz laimes dzimšanas dienā!', dutch: 'Gefeliciteerd met je verjaardag!', isSentence: true },
  { id: '115', latvian: 'Laimīgu Jauno gadu!', dutch: 'Gelukkig Nieuwjaar!', isSentence: true },
  { id: '116', latvian: 'Es kavēšu.', dutch: 'Ik zal laat zijn.', isSentence: true },
  { id: '117', latvian: 'Esmu gatavs.', dutch: 'Ik ben klaar.', isSentence: true },
  { id: '118', latvian: 'Pagaidi mirkli.', dutch: 'Wacht even.', isSentence: true },
  { id: '119', latvian: 'Apmēram stundu.', dutch: 'Ongeveer een uur.', isSentence: true },
  { id: '120', latvian: 'Katru dienu.', dutch: 'Elke dag.', isSentence: true },
  
  // --- RANDOM VERBS & NOUNS (10) ---
  { id: '121', latvian: 'Kaķis', dutch: 'Kat' },
  { id: '122', latvian: 'Suns', dutch: 'Hond' },
  { id: '123', latvian: 'Māja', dutch: 'Huis' },
  { id: '124', latvian: 'Strādāt', dutch: 'Werken' },
  { id: '125', latvian: 'Gulēt', dutch: 'Slapen' },
  { id: '126', latvian: 'Ēst', dutch: 'Eten' },
  { id: '127', latvian: 'Dzert', dutch: 'Drinken' },
  { id: '128', latvian: 'Lasīt', dutch: 'Lezen' },
  { id: '129', latvian: 'Rakstīt', dutch: 'Schrijven' },
  { id: '130', latvian: 'Ceļot', dutch: 'Reizen' },

  // --- COMMON EXPRESSIONS (10) ---
  { id: '131', latvian: 'Veiksmi!', dutch: 'Veel succes!', isSentence: true },
  { id: '132', latvian: 'Izklaidējies!', dutch: 'Veel plezier!', isSentence: true },
  { id: '133', latvian: 'Neuztraucies.', dutch: 'Maak je geen zorgen.', isSentence: true },
  { id: '134', latvian: 'Viss būs labi.', dutch: 'Alles komt goed.', isSentence: true },
  { id: '135', latvian: 'Man vienalga.', dutch: 'Het maakt mij niet uit.', isSentence: true },
  { id: '136', latvian: 'Tas ir atkarīgs.', dutch: 'Het hangt ervan af.', isSentence: true },
  { id: '137', latvian: 'Protams.', dutch: 'Natuurlijk.', isSentence: true },
  { id: '138', latvian: 'Varbūt vēlāk.', dutch: 'Misschien later.', isSentence: true },
  { id: '139', latvian: 'Es to ļoti gaidu.', dutch: 'Ik kijk ernaar uit.', isSentence: true },
  { id: '140', latvian: 'Tas nav tā vērts.', dutch: 'Het is het niet waard.', isSentence: true },

  // --- SOCIAL & PLANS (10) ---
  { id: '141', latvian: 'Ko tu dari?', dutch: 'Wat ben je aan het doen?', isSentence: true },
  { id: '142', latvian: 'Es neko nedaru.', dutch: 'Ik doe niets.', isSentence: true },
  { id: '143', latvian: 'Vai tu esi aizņemts?', dutch: 'Ben je druk?', isSentence: true },
  { id: '144', latvian: 'Esmu brīvs šovakar.', dutch: 'Ik ben vanavond vrij.', isSentence: true },
  { id: '145', latvian: 'Ejam uz kino.', dutch: 'Laten we naar de bioscoop gaan.', isSentence: true },
  { id: '146', latvian: 'Vai tu gribi kaut ko iedzert?', dutch: 'Wil je iets drinken?', isSentence: true },
  { id: '147', latvian: 'Kur mēs tiekamies?', dutch: 'Waar spreken we af?', isSentence: true },
  { id: '148', latvian: 'Cikos mēs tiekamies?', dutch: 'Hoe laat spreken we af?', isSentence: true },
  { id: '149', latvian: 'Esmu ceļā.', dutch: 'Ik ben onderweg.', isSentence: true },
  { id: '150', latvian: 'Es būšu klāt pēc piecām minūtēm.', dutch: 'Ik ben er over vijf minuten.', isSentence: true },

  // --- HEALTH & WELLBEING (10) ---
  { id: '151', latvian: 'Kā tu jūties?', dutch: 'Hoe voel je je?', isSentence: true },
  { id: '152', latvian: 'Es jūtos labi.', dutch: 'Ik voel me goed.', isSentence: true },
  { id: '153', latvian: 'Man sāp galva.', dutch: 'Ik heb hoofdpijn.', isSentence: true },
  { id: '154', latvian: 'Esmu saaukstējies.', dutch: 'Ik ben verkouden.', isSentence: true },
  { id: '155', latvian: 'Tev vajadzētu atpūsties.', dutch: 'Je moet rusten.', isSentence: true },
  { id: '156', latvian: 'Uz veselību!', dutch: 'Gezondheid!', isSentence: true }, // Context: sneezing
  { id: '157', latvian: 'Esi uzmanīgs.', dutch: 'Wees voorzichtig.', isSentence: true },
  { id: '158', latvian: 'Tas ir bīstami.', dutch: 'Dat is gevaarlijk.', isSentence: true },
  { id: '159', latvian: 'Izsauc ātro palīdzību.', dutch: 'Bel een ambulance.', isSentence: true },
  { id: '160', latvian: 'Man vajag zāles.', dutch: 'Ik heb medicijnen nodig.', isSentence: true },

  // --- PRACTICAL & TRAVEL NUANCES (10) ---
  { id: '161', latvian: 'Kur ir tuvākais bankomāts?', dutch: 'Waar is de dichtstbijzijnde geldautomaat?', isSentence: true },
  { id: '162', latvian: 'Vai varu maksāt skaidrā naudā?', dutch: 'Kan ik contant betalen?', isSentence: true },
  { id: '163', latvian: 'Saglabājiet atlikumu.', dutch: 'Hou het wisselgeld maar.', isSentence: true },
  { id: '164', latvian: 'Vai ir atlaide?', dutch: 'Is er korting?', isSentence: true },
  { id: '165', latvian: 'Es gribētu izīrēt velosipēdu.', dutch: 'Ik wil een fiets huren.', isSentence: true },
  { id: '166', latvian: 'Vai šis vieta ir brīva?', dutch: 'Is deze stoel vrij?', isSentence: true },
  { id: '167', latvian: 'Laimīgu ceļu!', dutch: 'Goede reis!', isSentence: true },
  { id: '168', latvian: 'Laiks ir briesmīgs.', dutch: 'Het weer is verschrikkelijk.', isSentence: true },
  { id: '169', latvian: 'Laukā ir auksts.', dutch: 'Het is koud buiten.', isSentence: true },
  { id: '170', latvian: 'Kādā krāsā tas ir?', dutch: 'Welke kleur is het?', isSentence: true },

  // --- WORK & TECHNOLOGY (10) ---
  { id: '171', latvian: 'Es strādāju birojā.', dutch: 'Ik werk op kantoor.', isSentence: true },
  { id: '172', latvian: 'Man ir sanāksme.', dutch: 'Ik heb een vergadering.', isSentence: true },
  { id: '173', latvian: 'Es nosūtīšu e-pastu.', dutch: 'Ik zal een e-mail sturen.', isSentence: true },
  { id: '174', latvian: 'Mana baterija ir tukša.', dutch: 'Mijn batterij is leeg.', isSentence: true },
  { id: '175', latvian: 'Vai tev ir lādētājs?', dutch: 'Heb je een oplader?', isSentence: true },
  { id: '176', latvian: 'Kāda ir parole?', dutch: 'Wat is het wachtwoord?', isSentence: true },
  { id: '177', latvian: 'Internets nedarbojas.', dutch: 'Het internet werkt niet.', isSentence: true },
  { id: '178', latvian: 'Es to atradīšu internetā.', dutch: 'Ik zoek het op internet.', isSentence: true },
  { id: '179', latvian: 'Lejupielādēt.', dutch: 'Downloaden.', isSentence: true },
  { id: '180', latvian: 'Nosūtīt ziņu.', dutch: 'Een bericht sturen.', isSentence: true },
];

export const getBaseVocabulary = (): VocabularyItem[] => {
  // Returns a shallow copy - vocabulary items are read-only so this is safe
  return [...initialVocabulary];
};
