import { VocabularyItem } from '../types';

const initialVocabulary: VocabularyItem[] = [
  // --- ESSENTIAL BASICS (20) ---
  { id: '1', latvian: 'Sveiki', dutch: 'Hallo', category: 'Basics' },
  { id: '2', latvian: 'Paldies', dutch: 'Dank je', category: 'Basics' },
  { id: '3', latvian: 'Lūdzu', dutch: 'Alsjeblieft', category: 'Basics' },
  { id: '4', latvian: 'Jā', dutch: 'Ja', category: 'Basics' },
  { id: '5', latvian: 'Nē', dutch: 'Nee', category: 'Basics' },
  { id: '6', latvian: 'Es', dutch: 'Ik', category: 'Basics' },
  { id: '7', latvian: 'Tu', dutch: 'Jij', category: 'Basics' },
  { id: '8', latvian: 'Viņš', dutch: 'Hij', category: 'Basics' },
  { id: '9', latvian: 'Viņa', dutch: 'Zij', category: 'Basics' },
  { id: '10', latvian: 'Mēs', dutch: 'Wij', category: 'Basics' },
  { id: '11', latvian: 'Labrīt', dutch: 'Goedemorgen', category: 'Basics' },
  { id: '12', latvian: 'Labdien', dutch: 'Goedemiddag', category: 'Basics' },
  { id: '13', latvian: 'Labvakar', dutch: 'Goedenavond', category: 'Basics' },
  { id: '14', latvian: 'Ar labunakti', dutch: 'Welterusten', category: 'Basics' },
  { id: '15', latvian: 'Uz redzēšanos', dutch: 'Tot ziens', category: 'Basics' },
  { id: '16', latvian: 'Kā iet?', dutch: 'Hoe gaat het?', category: 'Basics' },
  { id: '17', latvian: 'Labi', dutch: 'Goed', category: 'Basics' },
  { id: '18', latvian: 'Slikti', dutch: 'Slecht', category: 'Basics' },
  { id: '19', latvian: 'Atvainojiet', dutch: 'Pardon', category: 'Basics' },
  { id: '20', latvian: 'Nekas', dutch: 'Geen probleem', category: 'Basics' },

  // --- SENTENCES: INTRODUCTIONS (10) ---
  { id: '21', latvian: 'Kā tevi sauc?', dutch: 'Hoe heet je?', isSentence: true, category: 'Introductions' },
  { id: '22', latvian: 'Mani sauc Anna.', dutch: 'Ik heet Anna.', isSentence: true, category: 'Introductions' },
  { id: '23', latvian: 'Prieks iepazīties.', dutch: 'Leuk je te ontmoeten.', isSentence: true, category: 'Introductions' },
  { id: '24', latvian: 'No kurienes tu esi?', dutch: 'Waar kom je vandaan?', isSentence: true, category: 'Introductions' },
  { id: '25', latvian: 'Es esmu no Latvijas.', dutch: 'Ik kom uit Letland.', isSentence: true, category: 'Introductions' },
  { id: '26', latvian: 'Es esmu no Nīderlandes.', dutch: 'Ik kom uit Nederland.', isSentence: true, category: 'Introductions' },
  { id: '27', latvian: 'Kur tu dzīvo?', dutch: 'Waar woon je?', isSentence: true, category: 'Introductions' },
  { id: '28', latvian: 'Es dzīvoju Rīgā.', dutch: 'Ik woon in Riga.', isSentence: true, category: 'Introductions' },
  { id: '29', latvian: 'Cik tev ir gadu?', dutch: 'Hoe oud ben je?', isSentence: true, category: 'Introductions' },
  { id: '30', latvian: 'Es runāju nedaudz holandiešu valodā.', dutch: 'Ik spreek een beetje Nederlands.', isSentence: true, category: 'Introductions' },

  // --- SENTENCES: COMMUNICATION PROBLEMS (10) ---
  { id: '31', latvian: 'Vai jūs runājat angliski?', dutch: 'Spreekt u Engels?', isSentence: true, category: 'Communication' },
  { id: '32', latvian: 'Es nesaprotu.', dutch: 'Ik begrijp het niet.', isSentence: true, category: 'Communication' },
  { id: '33', latvian: 'Es nezinu.', dutch: 'Ik weet het niet.', isSentence: true, category: 'Communication' },
  { id: '34', latvian: 'Lūdzu, runājiet lēnāk.', dutch: 'Spreek langzamer alstublieft.', isSentence: true, category: 'Communication' },
  { id: '35', latvian: 'Ko tas nozīmē?', dutch: 'Wat betekent dat?', isSentence: true, category: 'Communication' },
  { id: '36', latvian: 'Vai varat to atkārtot?', dutch: 'Kunt u dat herhalen?', isSentence: true, category: 'Communication' },
  { id: '37', latvian: 'Lūdzu, uzrakstiet to.', dutch: 'Schrijf het alstublieft op.', isSentence: true, category: 'Communication' },
  { id: '38', latvian: 'Kā to pasaka holandiski?', dutch: 'Hoe zeg je dat in het Nederlands?', isSentence: true, category: 'Communication' },
  { id: '39', latvian: 'Man ir jautājums.', dutch: 'Ik heb een vraag.', isSentence: true, category: 'Communication' },
  { id: '40', latvian: 'Es mācos valodu.', dutch: 'Ik leer de taal.', isSentence: true, category: 'Communication' },

  // --- SENTENCES: TRAVEL & DIRECTIONS (15) ---
  { id: '41', latvian: 'Kur ir tualete?', dutch: 'Waar is het toilet?', isSentence: true, category: 'Travel' },
  { id: '42', latvian: 'Es meklēju staciju.', dutch: 'Ik zoek het station.', isSentence: true, category: 'Travel' },
  { id: '43', latvian: 'Kur ir lidosta?', dutch: 'Waar is de luchthaven?', isSentence: true, category: 'Travel' },
  { id: '44', latvian: 'Cik maksā biļete?', dutch: 'Hoeveel kost een kaartje?', isSentence: true, category: 'Travel' },
  { id: '45', latvian: 'Kad atiet vilciens?', dutch: 'Wanneer vertrekt de trein?', isSentence: true, category: 'Travel' },
  { id: '46', latvian: 'Kur ir viesnīca?', dutch: 'Waar is het hotel?', isSentence: true, category: 'Travel' },
  { id: '47', latvian: 'Pa labi.', dutch: 'Naar rechts.', isSentence: true, category: 'Travel' },
  { id: '48', latvian: 'Pa kreisi.', dutch: 'Naar links.', isSentence: true, category: 'Travel' },
  { id: '49', latvian: 'Taisni uz priekšu.', dutch: 'Rechtdoor.', isSentence: true, category: 'Travel' },
  { id: '50', latvian: 'Vai tas ir tālu?', dutch: 'Is het ver?', isSentence: true, category: 'Travel' },
  { id: '51', latvian: 'Pestājiet šeit, lūdzu.', dutch: 'Stop hier, alstublieft.', isSentence: true, category: 'Travel' },
  { id: '52', latvian: 'Es esmu apmaldījies.', dutch: 'Ik ben de weg kwijt.', isSentence: true, category: 'Travel' },
  { id: '53', latvian: 'Vai jūs varat man palīdzēt?', dutch: 'Kunt u mij helpen?', isSentence: true, category: 'Travel' },
  { id: '54', latvian: 'Kur es varu nopirkt biļeti?', dutch: 'Waar kan ik een kaartje kopen?', isSentence: true, category: 'Travel' },
  { id: '55', latvian: 'Uz centru, lūdzu.', dutch: 'Naar het centrum, alstublieft.', isSentence: true, category: 'Travel' },

  // --- SENTENCES: RESTAURANT & FOOD (15) ---
  { id: '56', latvian: 'Es gribētu galdiņu diviem.', dutch: 'Ik wil graag een tafel voor twee.', isSentence: true, category: 'Food' },
  { id: '57', latvian: 'Vai es varu redzēt ēdienkarti?', dutch: 'Mag ik de menukaart zien?', isSentence: true, category: 'Food' },
  { id: '58', latvian: 'Es esmu veģetārietis.', dutch: 'Ik ben vegetariër.', isSentence: true, category: 'Food' },
  { id: '59', latvian: 'Es gribētu ūdeni.', dutch: 'Ik wil graag water.', isSentence: true, category: 'Food' },
  { id: '60', latvian: 'Vienu alu, lūdzu.', dutch: 'Een bier, alstublieft.', isSentence: true, category: 'Food' },
  { id: '61', latvian: 'Rēķinu, lūdzu.', dutch: 'De rekening, alstublieft.', isSentence: true, category: 'Food' },
  { id: '62', latvian: 'Tas bija ļoti garšīgi.', dutch: 'Dat was erg lekker.', isSentence: true, category: 'Food' },
  { id: '63', latvian: 'Labu apetīti.', dutch: 'Eet smakelijk.', isSentence: true, category: 'Food' },
  { id: '64', latvian: 'Es gribētu kafiju.', dutch: 'Ik wil graag koffie.', isSentence: true, category: 'Food' },
  { id: '65', latvian: 'Vai jums ir brokastis?', dutch: 'Heeft u ontbijt?', isSentence: true, category: 'Food' },
  { id: '66', latvian: 'Es neēdu gaļu.', dutch: 'Ik eet geen vlees.', isSentence: true, category: 'Food' },
  { id: '67', latvian: 'Cik tas maksā?', dutch: 'Hoeveel kost dat?', isSentence: true, category: 'Food' },
  { id: '68', latvian: 'Vai varu maksāt ar karti?', dutch: 'Kan ik met kaart betalen?', isSentence: true, category: 'Food' },
  { id: '69', latvian: 'Mēs gribētu pasūtīt.', dutch: 'Wij willen graag bestellen.', isSentence: true, category: 'Food' },
  { id: '70', latvian: 'Uz veselību!', dutch: 'Proost!', isSentence: true, category: 'Food' },

  // --- SENTENCES: SHOPPING (10) ---
  { id: '71', latvian: 'Cikos veikals atveras?', dutch: 'Hoe laat gaat de winkel open?', isSentence: true, category: 'Shopping' },
  { id: '72', latvian: 'Cikos veikals slēdzas?', dutch: 'Hoe laat sluit de winkel?', isSentence: true, category: 'Shopping' },
  { id: '73', latvian: 'Es tikai skatos.', dutch: 'Ik ben alleen aan het kijken.', isSentence: true, category: 'Shopping' },
  { id: '74', latvian: 'Vai jums ir šis citā krāsā?', dutch: 'Heeft u dit in een andere kleur?', isSentence: true, category: 'Shopping' },
  { id: '75', latvian: 'Tas ir pārāk dārgs.', dutch: 'Dat is te duur.', isSentence: true, category: 'Shopping' },
  { id: '76', latvian: 'Es to ņemšu.', dutch: 'Ik neem het.', isSentence: true, category: 'Shopping' },
  { id: '77', latvian: 'Vai varu to pielaikot?', dutch: 'Kan ik dit passen?', isSentence: true, category: 'Shopping' },
  { id: '78', latvian: 'Kur ir ģērbtuve?', dutch: 'Waar is de paskamer?', isSentence: true, category: 'Shopping' },
  { id: '79', latvian: 'Vai jums ir maisiņš?', dutch: 'Heeft u een tasje?', isSentence: true, category: 'Shopping' },
  { id: '80', latvian: 'Izpārdošana.', dutch: 'Uitverkoop.', isSentence: true, category: 'Shopping' },

  // --- SENTENCES: EMERGENCIES (10) ---
  { id: '81', latvian: 'Palīgā!', dutch: 'Help!', isSentence: true, category: 'Emergencies' },
  { id: '82', latvian: 'Izsauciet policiju!', dutch: 'Bel de politie!', isSentence: true, category: 'Emergencies' },
  { id: '83', latvian: 'Man vajag ārstu.', dutch: 'Ik heb een dokter nodig.', isSentence: true, category: 'Emergencies' },
  { id: '84', latvian: 'Man sāp.', dutch: 'Ik heb pijn.', isSentence: true, category: 'Emergencies' },
  { id: '85', latvian: 'Es pazaudēju savu pasi.', dutch: 'Ik ben mijn paspoort kwijt.', isSentence: true, category: 'Emergencies' },
  { id: '86', latvian: 'Es pazaudēju savu telefonu.', dutch: 'Ik ben mijn telefoon kwijt.', isSentence: true, category: 'Emergencies' },
  { id: '87', latvian: 'Uzmanību!', dutch: 'Pas op!', isSentence: true, category: 'Emergencies' },
  { id: '88', latvian: 'Ugunsgrēks!', dutch: 'Brand!', isSentence: true, category: 'Emergencies' },
  { id: '89', latvian: 'Apstājieties!', dutch: 'Stop!', isSentence: true, category: 'Emergencies' },
  { id: '90', latvian: 'Kur ir slimnīca?', dutch: 'Waar is het ziekenhuis?', isSentence: true, category: 'Emergencies' },

  // --- SENTENCES: FEELINGS & OPINIONS (15) ---
  { id: '91', latvian: 'Es esmu noguris.', dutch: 'Ik ben moe.', isSentence: true, category: 'Feelings' },
  { id: '92', latvian: 'Es esmu laimīgs.', dutch: 'Ik ben gelukkig.', isSentence: true, category: 'Feelings' },
  { id: '93', latvian: 'Man ir garlaicīgi.', dutch: 'Ik verveel me.', isSentence: true, category: 'Feelings' },
  { id: '94', latvian: 'Man ir auksti.', dutch: 'Ik heb het koud.', isSentence: true, category: 'Feelings' },
  { id: '95', latvian: 'Man ir karsti.', dutch: 'Ik heb het warm.', isSentence: true, category: 'Feelings' },
  { id: '96', latvian: 'Es esmu izsalcis.', dutch: 'Ik heb honger.', isSentence: true, category: 'Feelings' },
  { id: '97', latvian: 'Es esmu izslāpis.', dutch: 'Ik heb dorst.', isSentence: true, category: 'Feelings' },
  { id: '98', latvian: 'Man tas patīk.', dutch: 'Ik vind het leuk.', isSentence: true, category: 'Feelings' },
  { id: '99', latvian: 'Man tas nepatīk.', dutch: 'Ik vind het niet leuk.', isSentence: true, category: 'Feelings' },
  { id: '100', latvian: 'Es tevi mīlu.', dutch: 'Ik hou van jou.', isSentence: true, category: 'Feelings' },
  { id: '101', latvian: 'Tas ir interesanti.', dutch: 'Dat is interessant.', isSentence: true, category: 'Feelings' },
  { id: '102', latvian: 'Tas ir smieklīgi.', dutch: 'Dat is grappig.', isSentence: true, category: 'Feelings' },
  { id: '103', latvian: 'Man ir bail.', dutch: 'Ik ben bang.', isSentence: true, category: 'Feelings' },
  { id: '104', latvian: 'Esmu pārsteigts.', dutch: 'Ik ben verbaasd.', isSentence: true, category: 'Feelings' },
  { id: '105', latvian: 'Es piekrītu.', dutch: 'Ik ben het ermee eens.', isSentence: true, category: 'Feelings' },

  // --- SENTENCES: TIME & WEATHER (15) ---
  { id: '106', latvian: 'Cik ir pulkstenis?', dutch: 'Hoe laat is het?', isSentence: true, category: 'Time & Weather' },
  { id: '107', latvian: 'Ir pulkstenis pieci.', dutch: 'Het is vijf uur.', isSentence: true, category: 'Time & Weather' },
  { id: '108', latvian: 'Šodien ir silts.', dutch: 'Het is warm vandaag.', isSentence: true, category: 'Time & Weather' },
  { id: '109', latvian: 'Lietus līst.', dutch: 'Het regent.', isSentence: true, category: 'Time & Weather' },
  { id: '110', latvian: 'Spīd saule.', dutch: 'De zon schijnt.', isSentence: true, category: 'Time & Weather' },
  { id: '111', latvian: 'Snieg sniegs.', dutch: 'Het sneeuwt.', isSentence: true, category: 'Time & Weather' },
  { id: '112', latvian: 'Ir vējains.', dutch: 'Het waait.', isSentence: true, category: 'Time & Weather' },
  { id: '113', latvian: 'Kāds šodien ir datums?', dutch: 'Welke datum is het vandaag?', isSentence: true, category: 'Time & Weather' },
  { id: '114', latvian: 'Daudz laimes dzimšanas dienā!', dutch: 'Gefeliciteerd met je verjaardag!', isSentence: true, category: 'Time & Weather' },
  { id: '115', latvian: 'Laimīgu Jauno gadu!', dutch: 'Gelukkig Nieuwjaar!', isSentence: true, category: 'Time & Weather' },
  { id: '116', latvian: 'Es kavēšu.', dutch: 'Ik zal laat zijn.', isSentence: true, category: 'Time & Weather' },
  { id: '117', latvian: 'Esmu gatavs.', dutch: 'Ik ben klaar.', isSentence: true, category: 'Time & Weather' },
  { id: '118', latvian: 'Pagaidi mirkli.', dutch: 'Wacht even.', isSentence: true, category: 'Time & Weather' },
  { id: '119', latvian: 'Apmēram stundu.', dutch: 'Ongeveer een uur.', isSentence: true, category: 'Time & Weather' },
  { id: '120', latvian: 'Katru dienu.', dutch: 'Elke dag.', isSentence: true, category: 'Time & Weather' },

  // --- RANDOM VERBS & NOUNS (10) ---
  { id: '121', latvian: 'Kaķis', dutch: 'Kat', category: 'Verbs & Nouns' },
  { id: '122', latvian: 'Suns', dutch: 'Hond', category: 'Verbs & Nouns' },
  { id: '123', latvian: 'Māja', dutch: 'Huis', category: 'Verbs & Nouns' },
  { id: '124', latvian: 'Strādāt', dutch: 'Werken', category: 'Verbs & Nouns' },
  { id: '125', latvian: 'Gulēt', dutch: 'Slapen', category: 'Verbs & Nouns' },
  { id: '126', latvian: 'Ēst', dutch: 'Eten', category: 'Verbs & Nouns' },
  { id: '127', latvian: 'Dzert', dutch: 'Drinken', category: 'Verbs & Nouns' },
  { id: '128', latvian: 'Lasīt', dutch: 'Lezen', category: 'Verbs & Nouns' },
  { id: '129', latvian: 'Rakstīt', dutch: 'Schrijven', category: 'Verbs & Nouns' },
  { id: '130', latvian: 'Ceļot', dutch: 'Reizen', category: 'Verbs & Nouns' },

  // --- COMMON EXPRESSIONS (10) ---
  { id: '131', latvian: 'Veiksmi!', dutch: 'Veel succes!', isSentence: true, category: 'Expressions' },
  { id: '132', latvian: 'Izklaidējies!', dutch: 'Veel plezier!', isSentence: true, category: 'Expressions' },
  { id: '133', latvian: 'Neuztraucies.', dutch: 'Maak je geen zorgen.', isSentence: true, category: 'Expressions' },
  { id: '134', latvian: 'Viss būs labi.', dutch: 'Alles komt goed.', isSentence: true, category: 'Expressions' },
  { id: '135', latvian: 'Man vienalga.', dutch: 'Het maakt mij niet uit.', isSentence: true, category: 'Expressions' },
  { id: '136', latvian: 'Tas ir atkarīgs.', dutch: 'Het hangt ervan af.', isSentence: true, category: 'Expressions' },
  { id: '137', latvian: 'Protams.', dutch: 'Natuurlijk.', isSentence: true, category: 'Expressions' },
  { id: '138', latvian: 'Varbūt vēlāk.', dutch: 'Misschien later.', isSentence: true, category: 'Expressions' },
  { id: '139', latvian: 'Es to ļoti gaidu.', dutch: 'Ik kijk ernaar uit.', isSentence: true, category: 'Expressions' },
  { id: '140', latvian: 'Tas nav tā vērts.', dutch: 'Het is het niet waard.', isSentence: true, category: 'Expressions' },

  // --- SOCIAL & PLANS (10) ---
  { id: '141', latvian: 'Ko tu dari?', dutch: 'Wat ben je aan het doen?', isSentence: true, category: 'Social' },
  { id: '142', latvian: 'Es neko nedaru.', dutch: 'Ik doe niets.', isSentence: true, category: 'Social' },
  { id: '143', latvian: 'Vai tu esi aizņemts?', dutch: 'Ben je druk?', isSentence: true, category: 'Social' },
  { id: '144', latvian: 'Esmu brīvs šovakar.', dutch: 'Ik ben vanavond vrij.', isSentence: true, category: 'Social' },
  { id: '145', latvian: 'Ejam uz kino.', dutch: 'Laten we naar de bioscoop gaan.', isSentence: true, category: 'Social' },
  { id: '146', latvian: 'Vai tu gribi kaut ko iedzert?', dutch: 'Wil je iets drinken?', isSentence: true, category: 'Social' },
  { id: '147', latvian: 'Kur mēs tiekamies?', dutch: 'Waar spreken we af?', isSentence: true, category: 'Social' },
  { id: '148', latvian: 'Cikos mēs tiekamies?', dutch: 'Hoe laat spreken we af?', isSentence: true, category: 'Social' },
  { id: '149', latvian: 'Esmu ceļā.', dutch: 'Ik ben onderweg.', isSentence: true, category: 'Social' },
  { id: '150', latvian: 'Es būšu klāt pēc piecām minūtēm.', dutch: 'Ik ben er over vijf minuten.', isSentence: true, category: 'Social' },

  // --- HEALTH & WELLBEING (10) ---
  { id: '151', latvian: 'Kā tu jūties?', dutch: 'Hoe voel je je?', isSentence: true, category: 'Health' },
  { id: '152', latvian: 'Es jūtos labi.', dutch: 'Ik voel me goed.', isSentence: true, category: 'Health' },
  { id: '153', latvian: 'Man sāp galva.', dutch: 'Ik heb hoofdpijn.', isSentence: true, category: 'Health' },
  { id: '154', latvian: 'Esmu saaukstējies.', dutch: 'Ik ben verkouden.', isSentence: true, category: 'Health' },
  { id: '155', latvian: 'Tev vajadzētu atpūsties.', dutch: 'Je moet rusten.', isSentence: true, category: 'Health' },
  { id: '156', latvian: 'Uz veselību!', dutch: 'Gezondheid!', isSentence: true, category: 'Health' },
  { id: '157', latvian: 'Esi uzmanīgs.', dutch: 'Wees voorzichtig.', isSentence: true, category: 'Health' },
  { id: '158', latvian: 'Tas ir bīstami.', dutch: 'Dat is gevaarlijk.', isSentence: true, category: 'Health' },
  { id: '159', latvian: 'Izsauc ātro palīdzību.', dutch: 'Bel een ambulance.', isSentence: true, category: 'Health' },
  { id: '160', latvian: 'Man vajag zāles.', dutch: 'Ik heb medicijnen nodig.', isSentence: true, category: 'Health' },

  // --- PRACTICAL & TRAVEL NUANCES (10) ---
  { id: '161', latvian: 'Kur ir tuvākais bankomāts?', dutch: 'Waar is de dichtstbijzijnde geldautomaat?', isSentence: true, category: 'Travel' },
  { id: '162', latvian: 'Vai varu maksāt skaidrā naudā?', dutch: 'Kan ik contant betalen?', isSentence: true, category: 'Travel' },
  { id: '163', latvian: 'Saglabājiet atlikumu.', dutch: 'Hou het wisselgeld maar.', isSentence: true, category: 'Travel' },
  { id: '164', latvian: 'Vai ir atlaide?', dutch: 'Is er korting?', isSentence: true, category: 'Travel' },
  { id: '165', latvian: 'Es gribētu izīrēt velosipēdu.', dutch: 'Ik wil een fiets huren.', isSentence: true, category: 'Travel' },
  { id: '166', latvian: 'Vai šis vieta ir brīva?', dutch: 'Is deze stoel vrij?', isSentence: true, category: 'Travel' },
  { id: '167', latvian: 'Laimīgu ceļu!', dutch: 'Goede reis!', isSentence: true, category: 'Travel' },
  { id: '168', latvian: 'Laiks ir briesmīgs.', dutch: 'Het weer is verschrikkelijk.', isSentence: true, category: 'Travel' },
  { id: '169', latvian: 'Laukā ir auksts.', dutch: 'Het is koud buiten.', isSentence: true, category: 'Travel' },
  { id: '170', latvian: 'Kādā krāsā tas ir?', dutch: 'Welke kleur is het?', isSentence: true, category: 'Travel' },

  // --- WORK & TECHNOLOGY (10) ---
  { id: '171', latvian: 'Es strādāju birojā.', dutch: 'Ik werk op kantoor.', isSentence: true, category: 'Work' },
  { id: '172', latvian: 'Man ir sanāksme.', dutch: 'Ik heb een vergadering.', isSentence: true, category: 'Work' },
  { id: '173', latvian: 'Es nosūtīšu e-pastu.', dutch: 'Ik zal een e-mail sturen.', isSentence: true, category: 'Work' },
  { id: '174', latvian: 'Mana baterija ir tukša.', dutch: 'Mijn batterij is leeg.', isSentence: true, category: 'Work' },
  { id: '175', latvian: 'Vai tev ir lādētājs?', dutch: 'Heb je een oplader?', isSentence: true, category: 'Work' },
  { id: '176', latvian: 'Kāda ir parole?', dutch: 'Wat is het wachtwoord?', isSentence: true, category: 'Work' },
  { id: '177', latvian: 'Internets nedarbojas.', dutch: 'Het internet werkt niet.', isSentence: true, category: 'Work' },
  { id: '178', latvian: 'Es to atradīšu internetā.', dutch: 'Ik zoek het op internet.', isSentence: true, category: 'Work' },
  { id: '179', latvian: 'Lejupielādēt.', dutch: 'Downloaden.', isSentence: true, category: 'Work' },
  { id: '180', latvian: 'Nosūtīt ziņu.', dutch: 'Een bericht sturen.', isSentence: true, category: 'Work' },

  // --- FAMILY & RELATIONSHIPS (10) ---
  { id: '181', latvian: 'Šī ir mana māte.', dutch: 'Dit is mijn moeder.', isSentence: true, category: 'Family' },
  { id: '182', latvian: 'Tas ir mans tēvs.', dutch: 'Dat is mijn vader.', isSentence: true, category: 'Family' },
  { id: '183', latvian: 'Man ir brālis.', dutch: 'Ik heb een broer.', isSentence: true, category: 'Family' },
  { id: '184', latvian: 'Man ir māsa.', dutch: 'Ik heb een zus.', isSentence: true, category: 'Family' },
  { id: '185', latvian: 'Viņi ir mani vecāki.', dutch: 'Zij zijn mijn ouders.', isSentence: true, category: 'Family' },
  { id: '186', latvian: 'Vai tev ir bērni?', dutch: 'Heb je kinderen?', isSentence: true, category: 'Family' },
  { id: '187', latvian: 'Man ir dēls.', dutch: 'Ik heb een zoon.', isSentence: true, category: 'Family' },
  { id: '188', latvian: 'Man ir meita.', dutch: 'Ik heb een dochter.', isSentence: true, category: 'Family' },
  { id: '189', latvian: 'Mēs esam precējušies.', dutch: 'Wij zijn getrouwd.', isSentence: true, category: 'Family' },
  { id: '190', latvian: 'Viņš ir mans draugs.', dutch: 'Hij is mijn vriend.', isSentence: true, category: 'Family' },

  // --- HOBBIES & INTERESTS (10) ---
  { id: '191', latvian: 'Man patīk lasīt grāmatas.', dutch: 'Ik hou van boeken lezen.', isSentence: true, category: 'Hobbies' },
  { id: '192', latvian: 'Es spēlēju futbolu.', dutch: 'Ik speel voetbal.', isSentence: true, category: 'Hobbies' },
  { id: '193', latvian: 'Vai tev patīk mūzika?', dutch: 'Hou je van muziek?', isSentence: true, category: 'Hobbies' },
  { id: '194', latvian: 'Es spēlēju ģitāru.', dutch: 'Ik speel gitaar.', isSentence: true, category: 'Hobbies' },
  { id: '195', latvian: 'Mums patīk ceļot.', dutch: 'Wij houden van reizen.', isSentence: true, category: 'Hobbies' },
  { id: '196', latvian: 'Es skatos filmas.', dutch: 'Ik kijk films.', isSentence: true, category: 'Hobbies' },
  { id: '197', latvian: 'Man patīk gatavot ēst.', dutch: 'Ik hou van koken.', isSentence: true, category: 'Hobbies' },
  { id: '198', latvian: 'Es eju uz sporta zāli.', dutch: 'Ik ga naar de sportschool.', isSentence: true, category: 'Hobbies' },
  { id: '199', latvian: 'Man patīk peldēt.', dutch: 'Ik hou van zwemmen.', isSentence: true, category: 'Hobbies' },
  { id: '200', latvian: 'Es kolekcionēju pastmarkas.', dutch: 'Ik verzamel postzegels.', isSentence: true, category: 'Hobbies' },

  // --- NATURE & ENVIRONMENT (10) ---
  { id: '201', latvian: 'Debesis ir zilas.', dutch: 'De lucht is blauw.', isSentence: true, category: 'Nature' },
  { id: '202', latvian: 'Zāle ir zaļa.', dutch: 'Het gras is groen.', isSentence: true, category: 'Nature' },
  { id: '203', latvian: 'Koki ir augsti.', dutch: 'De bomen zijn hoog.', isSentence: true, category: 'Nature' },
  { id: '204', latvian: 'Man patīk jūra.', dutch: 'Ik hou van de zee.', isSentence: true, category: 'Nature' },
  { id: '205', latvian: 'Mēs ejam uz mežu.', dutch: 'Wij gaan naar het bos.', isSentence: true, category: 'Nature' },
  { id: '206', latvian: 'Putni dzied.', dutch: 'De vogels zingen.', isSentence: true, category: 'Nature' },
  { id: '207', latvian: 'Ir pilnmēness.', dutch: 'Het is volle maan.', isSentence: true, category: 'Nature' },
  { id: '208', latvian: 'Zvaigznes ir skaistas.', dutch: 'De sterren zijn mooi.', isSentence: true, category: 'Nature' },
  { id: '209', latvian: 'Upē ir ūdens.', dutch: 'Er is water in de rivier.', isSentence: true, category: 'Nature' },
  { id: '210', latvian: 'Kalni ir tālu.', dutch: 'De bergen zijn ver weg.', isSentence: true, category: 'Nature' },

  // --- EDUCATION & LEARNING (10) ---
  { id: '211', latvian: 'Es studēju universitātē.', dutch: 'Ik studeer aan de universiteit.', isSentence: true, category: 'Education' },
  { id: '212', latvian: 'Man ir eksāmens rīt.', dutch: 'Ik heb morgen een examen.', isSentence: true, category: 'Education' },
  { id: '213', latvian: 'Es mācos vēsturi.', dutch: 'Ik studeer geschiedenis.', isSentence: true, category: 'Education' },
  { id: '214', latvian: 'Skolotājs ir gudrs.', dutch: 'De leraar is slim.', isSentence: true, category: 'Education' },
  { id: '215', latvian: 'Kur ir bibliotēka?', dutch: 'Waar is de bibliotheek?', isSentence: true, category: 'Education' },
  { id: '216', latvian: 'Man vajag pildspalvu.', dutch: 'Ik heb een pen nodig.', isSentence: true, category: 'Education' },
  { id: '217', latvian: 'Es lasu avīzi.', dutch: 'Ik lees de krant.', isSentence: true, category: 'Education' },
  { id: '218', latvian: 'Tas ir grūts uzdevums.', dutch: 'Dat is een moeilijke opdracht.', isSentence: true, category: 'Education' },
  { id: '219', latvian: 'Es gribu iemācīties vairāk.', dutch: 'Ik wil meer leren.', isSentence: true, category: 'Education' },
  { id: '220', latvian: 'Vai tu vari man palīdzēt ar mājasdarbiem?', dutch: 'Kun je me helpen met huiswerk?', isSentence: true, category: 'Education' },

  // --- DAILY ROUTINE (10) ---
  { id: '221', latvian: 'Es ceļos septiņos.', dutch: 'Ik sta om zeven uur op.', isSentence: true, category: 'Routine' },
  { id: '222', latvian: 'Es tīru zobus.', dutch: 'Ik poets mijn tanden.', isSentence: true, category: 'Routine' },
  { id: '223', latvian: 'Es eju dušā.', dutch: 'Ik neem een douche.', isSentence: true, category: 'Routine' },
  { id: '224', latvian: 'Es ēdu brokastis.', dutch: 'Ik eet ontbijt.', isSentence: true, category: 'Routine' },
  { id: '225', latvian: 'Es dzeru kafiju.', dutch: 'Ik drink koffie.', isSentence: true, category: 'Routine' },
  { id: '226', latvian: 'Es eju uz darbu.', dutch: 'Ik ga naar mijn werk.', isSentence: true, category: 'Routine' },
  { id: '227', latvian: 'Es pusdienoju divpadsmitos.', dutch: 'Ik lunch om twaalf uur.', isSentence: true, category: 'Routine' },
  { id: '228', latvian: 'Es nāku mājās sešos.', dutch: 'Ik kom om zes uur thuis.', isSentence: true, category: 'Routine' },
  { id: '229', latvian: 'Es skatos televizoru.', dutch: 'Ik kijk televisie.', isSentence: true, category: 'Routine' },
  { id: '230', latvian: 'Es eju gulēt desmitos.', dutch: 'Ik ga om tien uur slapen.', isSentence: true, category: 'Routine' },

  // --- HOUSE & HOME (10) ---
  { id: '231', latvian: 'Kur ir virtuve?', dutch: 'Waar is de keuken?', isSentence: true, category: 'House' },
  { id: '232', latvian: 'Vannas istaba ir tīra.', dutch: 'De badkamer is schoon.', isSentence: true, category: 'House' },
  { id: '233', latvian: 'Es esmu savā istabā.', dutch: 'Ik ben in mijn kamer.', isSentence: true, category: 'House' },
  { id: '234', latvian: 'Aizver logu, lūdzu.', dutch: 'Doe het raam dicht, alstublieft.', isSentence: true, category: 'House' },
  { id: '235', latvian: 'Atver durvis.', dutch: 'Doe de deur open.', isSentence: true, category: 'House' },
  { id: '236', latvian: 'Gaisma ir ieslēgta.', dutch: 'Het licht is aan.', isSentence: true, category: 'House' },
  { id: '237', latvian: 'Izslēdz gaismu.', dutch: 'Doe het licht uit.', isSentence: true, category: 'House' },
  { id: '238', latvian: 'Mums ir dārzs.', dutch: 'Wij hebben een tuin.', isSentence: true, category: 'House' },
  { id: '239', latvian: 'Kur ir atslēgas?', dutch: 'Waar zijn de sleutels?', isSentence: true, category: 'House' },
  { id: '240', latvian: 'Māja ir liela.', dutch: 'Het huis is groot.', isSentence: true, category: 'House' },

  // --- TRANSPORTATION (10) ---
  { id: '241', latvian: 'Es braucu ar mašīnu.', dutch: 'Ik rijd met de auto.', isSentence: true, category: 'Transport' },
  { id: '242', latvian: 'Es braucu ar autobusu.', dutch: 'Ik ga met de bus.', isSentence: true, category: 'Transport' },
  { id: '243', latvian: 'Es braucu ar velosipēdu.', dutch: 'Ik fiets.', isSentence: true, category: 'Transport' },
  { id: '244', latvian: 'Luksofors ir sarkans.', dutch: 'Het stoplicht is rood.', isSentence: true, category: 'Transport' },
  { id: '245', latvian: 'Luksofors ir zaļš.', dutch: 'Het stoplicht is groen.', isSentence: true, category: 'Transport' },
  { id: '246', latvian: 'Uzmanies uz ceļa.', dutch: 'Pas op op de weg.', isSentence: true, category: 'Transport' },
  { id: '247', latvian: 'Kur es varu novietot auto?', dutch: 'Waar kan ik parkeren?', isSentence: true, category: 'Transport' },
  { id: '248', latvian: 'Degviela ir dārga.', dutch: 'Benzine is duur.', isSentence: true, category: 'Transport' },
  { id: '249', latvian: 'Man ir riepa caura.', dutch: 'Ik heb een lekke band.', isSentence: true, category: 'Transport' },
  { id: '250', latvian: 'Izsauc taksometru.', dutch: 'Bel een taxi.', isSentence: true, category: 'Transport' },

  // --- SHOPPING (10) ---
  { id: '251', latvian: 'Man vajag maizi.', dutch: 'Ik heb brood nodig.', isSentence: true, category: 'Shopping' },
  { id: '252', latvian: 'Es pērku pienu.', dutch: 'Ik koop melk.', isSentence: true, category: 'Shopping' },
  { id: '253', latvian: 'Vai jums ir olas?', dutch: 'Heeft u eieren?', isSentence: true, category: 'Shopping' },
  { id: '254', latvian: 'Es gribu nopirkt augļus.', dutch: 'Ik wil fruit kopen.', isSentence: true, category: 'Shopping' },
  { id: '255', latvian: 'Dārzeņi ir svaigi.', dutch: 'De groenten zijn vers.', isSentence: true, category: 'Shopping' },
  { id: '256', latvian: 'Cik maksā siers?', dutch: 'Hoeveel kost de kaas?', isSentence: true, category: 'Shopping' },
  { id: '257', latvian: 'Man vajag maisiņu.', dutch: 'Ik heb een tasje nodig.', isSentence: true, category: 'Shopping' },
  { id: '258', latvian: 'Kur ir kase?', dutch: 'Waar is de kassa?', isSentence: true, category: 'Shopping' },
  { id: '259', latvian: 'Es maksāšu ar skaidru naudu.', dutch: 'Ik betaal contant.', isSentence: true, category: 'Shopping' },
  { id: '260', latvian: 'Paldies par pirkumu.', dutch: 'Bedankt voor uw aankoop.', isSentence: true, category: 'Shopping' },

  // --- EMOTIONS & STATES (10) ---
  { id: '261', latvian: 'Es esmu dusmīgs.', dutch: 'Ik ben boos.', isSentence: true, category: 'Emotions' },
  { id: '262', latvian: 'Viņa ir bēdīga.', dutch: 'Zij is verdrietig.', isSentence: true, category: 'Emotions' },
  { id: '263', latvian: 'Mēs esam satraukti.', dutch: 'Wij zijn opgewonden.', isSentence: true, category: 'Emotions' },
  { id: '264', latvian: 'Es esmu noraizējies.', dutch: 'Ik ben bezorgd.', isSentence: true, category: 'Emotions' },
  { id: '265', latvian: 'Es jūtos slims.', dutch: 'Ik voel me ziek.', isSentence: true, category: 'Emotions' },
  { id: '266', latvian: 'Tas ir pretīgi.', dutch: 'Dat is walgelijk.', isSentence: true, category: 'Emotions' },
  { id: '267', latvian: 'Tas ir brīnišķīgi.', dutch: 'Dat is geweldig.', isSentence: true, category: 'Emotions' },
  { id: '268', latvian: 'Es esmu vīlies.', dutch: 'Ik ben teleurgesteld.', isSentence: true, category: 'Emotions' },
  { id: '269', latvian: 'Es esmu lepns.', dutch: 'Ik ben trots.', isSentence: true, category: 'Emotions' },
  { id: '270', latvian: 'Es esmu apmulsis.', dutch: 'Ik ben in de war.', isSentence: true, category: 'Emotions' },

  // --- MISCELLANEOUS (10) ---
  { id: '271', latvian: 'Kas notika?', dutch: 'Wat is er gebeurd?', isSentence: true, category: 'Misc' },
  { id: '272', latvian: 'Tas nav svarīgi.', dutch: 'Dat is niet belangrijk.', isSentence: true, category: 'Misc' },
  { id: '273', latvian: 'Es jokoju.', dutch: 'Ik maak een grapje.', isSentence: true, category: 'Misc' },
  { id: '274', latvian: 'Tā ir taisnība.', dutch: 'Dat is waar.', isSentence: true, category: 'Misc' },
  { id: '275', latvian: 'Tie ir meli.', dutch: 'Dat is een leugen.', isSentence: true, category: 'Misc' },
  { id: '276', latvian: 'Es tev ticu.', dutch: 'Ik geloof je.', isSentence: true, category: 'Misc' },
  { id: '277', latvian: 'Es tev neticu.', dutch: 'Ik geloof je niet.', isSentence: true, category: 'Misc' },
  { id: '278', latvian: 'Aizmirsti to.', dutch: 'Vergeet het maar.', isSentence: true, category: 'Misc' },
  { id: '279', latvian: 'Lai veicas!', dutch: 'Veel geluk!', isSentence: true, category: 'Misc' },
  { id: '280', latvian: 'Uz drīzu tikšanos!', dutch: 'Tot snel!', isSentence: true, category: 'Misc' },

  // --- COLORS & SHAPES (10) ---
  { id: '281', latvian: 'Sarkans', dutch: 'Rood', category: 'Colors & Shapes' },
  { id: '282', latvian: 'Zils', dutch: 'Blauw', category: 'Colors & Shapes' },
  { id: '283', latvian: 'Zaļš', dutch: 'Groen', category: 'Colors & Shapes' },
  { id: '284', latvian: 'Dzeltens', dutch: 'Geel', category: 'Colors & Shapes' },
  { id: '285', latvian: 'Melns', dutch: 'Zwart', category: 'Colors & Shapes' },
  { id: '286', latvian: 'Balts', dutch: 'Wit', category: 'Colors & Shapes' },
  { id: '287', latvian: 'Aplis', dutch: 'Cirkel', category: 'Colors & Shapes' },
  { id: '288', latvian: 'Kvadrāts', dutch: 'Vierkant', category: 'Colors & Shapes' },
  { id: '289', latvian: 'Trīsstūris', dutch: 'Driehoek', category: 'Colors & Shapes' },
  { id: '290', latvian: 'Krāsa', dutch: 'Kleur', category: 'Colors & Shapes' },

  // --- BODY PARTS (10) ---
  { id: '291', latvian: 'Galva', dutch: 'Hoofd', category: 'Body Parts' },
  { id: '292', latvian: 'Roka', dutch: 'Hand', category: 'Body Parts' },
  { id: '293', latvian: 'Kāja', dutch: 'Been', category: 'Body Parts' },
  { id: '294', latvian: 'Acis', dutch: 'Ogen', category: 'Body Parts' },
  { id: '295', latvian: 'Deguns', dutch: 'Neus', category: 'Body Parts' },
  { id: '296', latvian: 'Mute', dutch: 'Mond', category: 'Body Parts' },
  { id: '297', latvian: 'Ausis', dutch: 'Oren', category: 'Body Parts' },
  { id: '298', latvian: 'Mati', dutch: 'Haar', category: 'Body Parts' },
  { id: '299', latvian: 'Pirksts', dutch: 'Vinger', category: 'Body Parts' },
  { id: '300', latvian: 'Mugura', dutch: 'Rug', category: 'Body Parts' },

  // --- CLOTHING & ACCESSORIES (10) ---
  { id: '301', latvian: 'Krekls', dutch: 'Overhemd', category: 'Clothing & Accessories' },
  { id: '302', latvian: 'Bikses', dutch: 'Broek', category: 'Clothing & Accessories' },
  { id: '303', latvian: 'Kleita', dutch: 'Jurk', category: 'Clothing & Accessories' },
  { id: '304', latvian: 'Kurpes', dutch: 'Schoenen', category: 'Clothing & Accessories' },
  { id: '305', latvian: 'Cepure', dutch: 'Hoed', category: 'Clothing & Accessories' },
  { id: '306', latvian: 'Mētelis', dutch: 'Jas', category: 'Clothing & Accessories' },
  { id: '307', latvian: 'Zeķes', dutch: 'Sokken', category: 'Clothing & Accessories' },
  { id: '308', latvian: 'Svārki', dutch: 'Rok', category: 'Clothing & Accessories' },
  { id: '309', latvian: 'Brilles', dutch: 'Bril', category: 'Clothing & Accessories' },
  { id: '310', latvian: 'Soma', dutch: 'Tas', category: 'Clothing & Accessories' },

  // --- ANIMALS (10) ---
  { id: '311', latvian: 'Lācis', dutch: 'Beer', category: 'Animals' },
  { id: '312', latvian: 'Vilks', dutch: 'Wolf', category: 'Animals' },
  { id: '313', latvian: 'Lapsa', dutch: 'Vos', category: 'Animals' },
  { id: '314', latvian: 'Zaķis', dutch: 'Haas', category: 'Animals' },
  { id: '315', latvian: 'Zirgs', dutch: 'Paard', category: 'Animals' },
  { id: '316', latvian: 'Govs', dutch: 'Koe', category: 'Animals' },
  { id: '317', latvian: 'Cūka', dutch: 'Varken', category: 'Animals' },
  { id: '318', latvian: 'Putns', dutch: 'Vogel', category: 'Animals' },
  { id: '319', latvian: 'Zivs', dutch: 'Vis', category: 'Animals' },
  { id: '320', latvian: 'Pele', dutch: 'Muis', category: 'Animals' },

  // --- FRUITS & VEGETABLES (10) ---
  { id: '321', latvian: 'Ābols', dutch: 'Appel', category: 'Fruits & Vegetables' },
  { id: '322', latvian: 'Bumbieris', dutch: 'Peer', category: 'Fruits & Vegetables' },
  { id: '323', latvian: 'Banāns', dutch: 'Banaan', category: 'Fruits & Vegetables' },
  { id: '324', latvian: 'Apelsīns', dutch: 'Sinaasappel', category: 'Fruits & Vegetables' },
  { id: '325', latvian: 'Kartupelis', dutch: 'Aardappel', category: 'Fruits & Vegetables' },
  { id: '326', latvian: 'Burkāns', dutch: 'Wortel', category: 'Fruits & Vegetables' },
  { id: '327', latvian: 'Sīpols', dutch: 'Ui', category: 'Fruits & Vegetables' },
  { id: '328', latvian: 'Gurķis', dutch: 'Komkommer', category: 'Fruits & Vegetables' },
  { id: '329', latvian: 'Tomāts', dutch: 'Tomaat', category: 'Fruits & Vegetables' },
  { id: '330', latvian: 'Kāposts', dutch: 'Kool', category: 'Fruits & Vegetables' },

  // --- DRINKS & BEVERAGES (10) ---
  { id: '331', latvian: 'Ūdens', dutch: 'Water', category: 'Drinks & Beverages' },
  { id: '332', latvian: 'Tēja', dutch: 'Thee', category: 'Drinks & Beverages' },
  { id: '333', latvian: 'Kafija', dutch: 'Koffie', category: 'Drinks & Beverages' },
  { id: '334', latvian: 'Sula', dutch: 'Sap', category: 'Drinks & Beverages' },
  { id: '335', latvian: 'Piens', dutch: 'Melk', category: 'Drinks & Beverages' },
  { id: '336', latvian: 'Alus', dutch: 'Bier', category: 'Drinks & Beverages' },
  { id: '337', latvian: 'Vīns', dutch: 'Wijn', category: 'Drinks & Beverages' },
  { id: '338', latvian: 'Limonāde', dutch: 'Limonade', category: 'Drinks & Beverages' },
  { id: '339', latvian: 'Kokteilis', dutch: 'Cocktail', category: 'Drinks & Beverages' },
  { id: '340', latvian: 'Ledus', dutch: 'IJs', category: 'Drinks & Beverages' },

  // --- SPORTS & ACTIVITIES (10) ---
  { id: '341', latvian: 'Futbols', dutch: 'Voetbal', category: 'Sports & Activities' },
  { id: '342', latvian: 'Basketbols', dutch: 'Basketbal', category: 'Sports & Activities' },
  { id: '343', latvian: 'Hokejs', dutch: 'Ijshockey', category: 'Sports & Activities' },
  { id: '344', latvian: 'Teniss', dutch: 'Tennis', category: 'Sports & Activities' },
  { id: '345', latvian: 'Peldēšana', dutch: 'Zwemmen', category: 'Sports & Activities' },
  { id: '346', latvian: 'Skriešana', dutch: 'Hardlopen', category: 'Sports & Activities' },
  { id: '347', latvian: 'Riteņbraukšana', dutch: 'Fietsen', category: 'Sports & Activities' },
  { id: '348', latvian: 'Slēpošana', dutch: 'Skiën', category: 'Sports & Activities' },
  { id: '349', latvian: 'Dejošana', dutch: 'Dansen', category: 'Sports & Activities' },
  { id: '350', latvian: 'Pastaiga', dutch: 'Wandelen', category: 'Sports & Activities' },

  // --- PROFESSIONS & JOBS (10) ---
  { id: '351', latvian: 'Ārsts', dutch: 'Dokter', category: 'Professions & Jobs' },
  { id: '352', latvian: 'Skolotājs', dutch: 'Leraar', category: 'Professions & Jobs' },
  { id: '353', latvian: 'Inženieris', dutch: 'Ingenieur', category: 'Professions & Jobs' },
  { id: '354', latvian: 'Pavārs', dutch: 'Kok', category: 'Professions & Jobs' },
  { id: '355', latvian: 'Policists', dutch: 'Politieagent', category: 'Professions & Jobs' },
  { id: '356', latvian: 'Ugunsdzēsējs', dutch: 'Brandweerman', category: 'Professions & Jobs' },
  { id: '357', latvian: 'Pārdevējs', dutch: 'Verkoper', category: 'Professions & Jobs' },
  { id: '358', latvian: 'Vadītājs', dutch: 'Chauffeur', category: 'Professions & Jobs' },
  { id: '359', latvian: 'Mākslinieks', dutch: 'Kunstenaar', category: 'Professions & Jobs' },
  { id: '360', latvian: 'Zemnieks', dutch: 'Boer', category: 'Professions & Jobs' },

  // --- COUNTRIES & NATIONALITIES (10) ---
  { id: '361', latvian: 'Latvija', dutch: 'Letland', category: 'Countries & Nationalities' },
  { id: '362', latvian: 'Nīderlande', dutch: 'Nederland', category: 'Countries & Nationalities' },
  { id: '363', latvian: 'Igaunija', dutch: 'Estland', category: 'Countries & Nationalities' },
  { id: '364', latvian: 'Lietuva', dutch: 'Litouwen', category: 'Countries & Nationalities' },
  { id: '365', latvian: 'Vācija', dutch: 'Duitsland', category: 'Countries & Nationalities' },
  { id: '366', latvian: 'Francija', dutch: 'Frankrijk', category: 'Countries & Nationalities' },
  { id: '367', latvian: 'Anglija', dutch: 'Engeland', category: 'Countries & Nationalities' },
  { id: '368', latvian: 'Eiropa', dutch: 'Europa', category: 'Countries & Nationalities' },
  { id: '369', latvian: 'Amerika', dutch: 'Amerika', category: 'Countries & Nationalities' },
  { id: '370', latvian: 'Pasaule', dutch: 'Wereld', category: 'Countries & Nationalities' },

  // --- MONTHS, DAYS & SEASONS (10) ---
  { id: '371', latvian: 'Janvāris', dutch: 'Januari', category: 'Months, Days & Seasons' },
  { id: '372', latvian: 'Februāris', dutch: 'Februari', category: 'Months, Days & Seasons' },
  { id: '373', latvian: 'Pirmdiena', dutch: 'Maandag', category: 'Months, Days & Seasons' },
  { id: '374', latvian: 'Otrdiena', dutch: 'Dinsdag', category: 'Months, Days & Seasons' },
  { id: '375', latvian: 'Pavasaris', dutch: 'Lente', category: 'Months, Days & Seasons' },
  { id: '376', latvian: 'Vasara', dutch: 'Zomer', category: 'Months, Days & Seasons' },
  { id: '377', latvian: 'Rudens', dutch: 'Herfst', category: 'Months, Days & Seasons' },
  { id: '378', latvian: 'Ziema', dutch: 'Winter', category: 'Months, Days & Seasons' },
  { id: '379', latvian: 'Nedēļa', dutch: 'Week', category: 'Months, Days & Seasons' },
  { id: '380', latvian: 'Gads', dutch: 'Jaar', category: 'Months, Days & Seasons' },

  // --- NUMBERS & MATH (10) ---
  { id: '381', latvian: 'Nulle', dutch: 'Nul', category: 'Numbers & Math' },
  { id: '382', latvian: 'Viens', dutch: 'Een', category: 'Numbers & Math' },
  { id: '383', latvian: 'Divi', dutch: 'Twee', category: 'Numbers & Math' },
  { id: '384', latvian: 'Trīs', dutch: 'Drie', category: 'Numbers & Math' },
  { id: '385', latvian: 'Desmit', dutch: 'Tien', category: 'Numbers & Math' },
  { id: '386', latvian: 'Simts', dutch: 'Honderd', category: 'Numbers & Math' },
  { id: '387', latvian: 'Tūkstotis', dutch: 'Duizend', category: 'Numbers & Math' },
  { id: '388', latvian: 'Puse', dutch: 'Helft', category: 'Numbers & Math' },
  { id: '389', latvian: 'Daudz', dutch: 'Veel', category: 'Numbers & Math' },
  { id: '390', latvian: 'Maz', dutch: 'Weinig', category: 'Numbers & Math' },

  // --- ORDINAL NUMBERS (10) ---
  { id: '391', latvian: 'Pirmais', dutch: 'Eerste', category: 'Ordinal Numbers' },
  { id: '392', latvian: 'Otrais', dutch: 'Tweede', category: 'Ordinal Numbers' },
  { id: '393', latvian: 'Trešais', dutch: 'Derde', category: 'Ordinal Numbers' },
  { id: '394', latvian: 'Ceturtais', dutch: 'Vierde', category: 'Ordinal Numbers' },
  { id: '395', latvian: 'Piektais', dutch: 'Vijfde', category: 'Ordinal Numbers' },
  { id: '396', latvian: 'Sestais', dutch: 'Zesde', category: 'Ordinal Numbers' },
  { id: '397', latvian: 'Septītais', dutch: 'Zevende', category: 'Ordinal Numbers' },
  { id: '398', latvian: 'Astotais', dutch: 'Achtste', category: 'Ordinal Numbers' },
  { id: '399', latvian: 'Devītais', dutch: 'Negende', category: 'Ordinal Numbers' },
  { id: '400', latvian: 'Desmitais', dutch: 'Tiende', category: 'Ordinal Numbers' },

  // --- ADJECTIVES & OPPOSITES (20) ---
  { id: '401', latvian: 'Liels', dutch: 'Groot', category: 'Adjectives' },
  { id: '402', latvian: 'Mazs', dutch: 'Klein', category: 'Adjectives' },
  { id: '403', latvian: 'Garš', dutch: 'Lang', category: 'Adjectives' },
  { id: '404', latvian: 'Īss', dutch: 'Kort', category: 'Adjectives' },
  { id: '405', latvian: 'Jauns', dutch: 'Nieuw', category: 'Adjectives' },
  { id: '406', latvian: 'Vecs', dutch: 'Oud', category: 'Adjectives' },
  { id: '407', latvian: 'Labs', dutch: 'Goed', category: 'Adjectives' },
  { id: '408', latvian: 'Slikts', dutch: 'Slecht', category: 'Adjectives' },
  { id: '409', latvian: 'Karsts', dutch: 'Heet', category: 'Adjectives' },
  { id: '410', latvian: 'Auksts', dutch: 'Koud', category: 'Adjectives' },
  { id: '411', latvian: 'Ātrs', dutch: 'Snel', category: 'Adjectives' },
  { id: '412', latvian: 'Lēns', dutch: 'Langzaam', category: 'Adjectives' },
  { id: '413', latvian: 'Smags', dutch: 'Zwaar', category: 'Adjectives' },
  { id: '414', latvian: 'Viegls', dutch: 'Licht', category: 'Adjectives' },
  { id: '415', latvian: 'Pilns', dutch: 'Vol', category: 'Adjectives' },
  { id: '416', latvian: 'Tukšs', dutch: 'Leeg', category: 'Adjectives' },
  { id: '417', latvian: 'Tīrs', dutch: 'Schoon', category: 'Adjectives' },
  { id: '418', latvian: 'Netīrs', dutch: 'Vuil', category: 'Adjectives' },
  { id: '419', latvian: 'Skaists', dutch: 'Mooi', category: 'Adjectives' },
  { id: '420', latvian: 'Neglīts', dutch: 'Lelijk', category: 'Adjectives' },

  // --- PREPOSITIONS & DIRECTIONS (10) ---
  { id: '421', latvian: 'Uz', dutch: 'Op', category: 'Prepositions' },
  { id: '422', latvian: 'Zem', dutch: 'Onder', category: 'Prepositions' },
  { id: '423', latvian: 'Iekša', dutch: 'In', category: 'Prepositions' },
  { id: '424', latvian: 'Ārā', dutch: 'Uit', category: 'Prepositions' },
  { id: '425', latvian: 'Pie', dutch: 'Bij', category: 'Prepositions' },
  { id: '426', latvian: 'Ar', dutch: 'Met', category: 'Prepositions' },
  { id: '427', latvian: 'Bez', dutch: 'Zonder', category: 'Prepositions' },
  { id: '428', latvian: 'Pirms', dutch: 'Voor', category: 'Prepositions' },
  { id: '429', latvian: 'Pēc', dutch: 'Na', category: 'Prepositions' },
  { id: '430', latvian: 'Starp', dutch: 'Tussen', category: 'Prepositions' },

  // --- CONJUNCTIONS & CONNECTORS (10) ---
  { id: '431', latvian: 'Un', dutch: 'En', category: 'Conjunctions' },
  { id: '432', latvian: 'Bet', dutch: 'Maar', category: 'Conjunctions' },
  { id: '433', latvian: 'Vai', dutch: 'Of', category: 'Conjunctions' },
  { id: '434', latvian: 'Jo', dutch: 'Omdat', category: 'Conjunctions' },
  { id: '435', latvian: 'Ja', dutch: 'Als', category: 'Conjunctions' },
  { id: '436', latvian: 'Tāpēc', dutch: 'Daarom', category: 'Conjunctions' },
  { id: '437', latvian: 'Lai', dutch: 'Zodat', category: 'Conjunctions' },
  { id: '438', latvian: 'Kaut arī', dutch: 'Hoewel', category: 'Conjunctions' },
  { id: '439', latvian: 'Tomēr', dutch: 'Echter', category: 'Conjunctions' },
  { id: '440', latvian: 'Arī', dutch: 'Ook', category: 'Conjunctions' },

  // --- QUESTION WORDS (10) ---
  { id: '441', latvian: 'Kas?', dutch: 'Wie/Wat?', category: 'Questions' },
  { id: '442', latvian: 'Kur?', dutch: 'Waar?', category: 'Questions' },
  { id: '443', latvian: 'Kad?', dutch: 'Wanneer?', category: 'Questions' },
  { id: '444', latvian: 'Kāpēc?', dutch: 'Waarom?', category: 'Questions' },
  { id: '445', latvian: 'Kā?', dutch: 'Hoe?', category: 'Questions' },
  { id: '446', latvian: 'Kurš?', dutch: 'Welke?', category: 'Questions' },
  { id: '447', latvian: 'Cik daudz?', dutch: 'Hoeveel?', category: 'Questions' },
  { id: '448', latvian: 'Cik ilgi?', dutch: 'Hoe lang?', category: 'Questions' },
  { id: '449', latvian: 'Uz kurieni?', dutch: 'Waarheen?', category: 'Questions' },
  { id: '450', latvian: 'No kurienes?', dutch: 'Waarvandaan?', category: 'Questions' },

  // --- TECHNOLOGY (10) ---
  { id: '451', latvian: 'Dators', dutch: 'Computer', category: 'Technology' },
  { id: '452', latvian: 'Telefons', dutch: 'Telefoon', category: 'Technology' },
  { id: '453', latvian: 'Ekrāns', dutch: 'Scherm', category: 'Technology' },
  { id: '454', latvian: 'Pele', dutch: 'Muis', category: 'Technology' }, // Note: 'Pele' is also mouse animal, context differs.
  { id: '455', latvian: 'Tastatūra', dutch: 'Toetsenbord', category: 'Technology' },
  { id: '456', latvian: 'Internets', dutch: 'Internet', category: 'Technology' },
  { id: '457', latvian: 'Programma', dutch: 'Programma', category: 'Technology' },
  { id: '458', latvian: 'Fails', dutch: 'Bestand', category: 'Technology' },
  { id: '459', latvian: 'Mape', dutch: 'Map', category: 'Technology' },
  { id: '460', latvian: 'Saite', dutch: 'Link', category: 'Technology' },

  // --- KITCHEN & COOKING (20) ---
  { id: '461', latvian: 'Virtuve', dutch: 'Keuken', category: 'Kitchen' },
  { id: '462', latvian: 'Galds', dutch: 'Tafel', category: 'Kitchen' },
  { id: '463', latvian: 'Krēsls', dutch: 'Stoel', category: 'Kitchen' },
  { id: '464', latvian: 'Ledusskapis', dutch: 'Koelkast', category: 'Kitchen' },
  { id: '465', latvian: 'Plīts', dutch: 'Fornuis', category: 'Kitchen' },
  { id: '466', latvian: 'Cepeškrāsns', dutch: 'Oven', category: 'Kitchen' },
  { id: '467', latvian: 'Dakša', dutch: 'Vork', category: 'Kitchen' },
  { id: '468', latvian: 'Nazis', dutch: 'Mes', category: 'Kitchen' },
  { id: '469', latvian: 'Karote', dutch: 'Lepel', category: 'Kitchen' },
  { id: '470', latvian: 'Šķīvis', dutch: 'Bord', category: 'Kitchen' },
  { id: '471', latvian: 'Krūze', dutch: 'Mok', category: 'Kitchen' },
  { id: '472', latvian: 'Glāze', dutch: 'Glas', category: 'Kitchen' },
  { id: '473', latvian: 'Panna', dutch: 'Pan', category: 'Kitchen' },
  { id: '474', latvian: 'Katls', dutch: 'Kookpot', category: 'Kitchen' },
  { id: '475', latvian: 'Bļoda', dutch: 'Kom', category: 'Kitchen' },
  { id: '476', latvian: 'Brokastis', dutch: 'Ontbijt', category: 'Kitchen' },
  { id: '477', latvian: 'Pusdienas', dutch: 'Lunch', category: 'Kitchen' },
  { id: '478', latvian: 'Vakariņas', dutch: 'Diner', category: 'Kitchen' },
  { id: '479', latvian: 'Sāls', dutch: 'Zout', category: 'Kitchen' },
  { id: '480', latvian: 'Pipari', dutch: 'Peper', category: 'Kitchen' },

  // --- HEALTH & MEDICAL (20) ---
  { id: '481', latvian: 'Veselība', dutch: 'Gezondheid', category: 'Health' },
  { id: '482', latvian: 'Slimnīca', dutch: 'Ziekenhuis', category: 'Health' },
  { id: '483', latvian: 'Ārsts', dutch: 'Dokter', category: 'Health' }, // Duplicate of profession, but useful in context
  { id: '484', latvian: 'Zāles', dutch: 'Medicijnen', category: 'Health' },
  { id: '485', latvian: 'Aptieka', dutch: 'Apotheek', category: 'Health' },
  { id: '486', latvian: 'Sāpes', dutch: 'Pijn', category: 'Health' },
  { id: '487', latvian: 'Drudzis', dutch: 'Koorts', category: 'Health' },
  { id: '488', latvian: 'Klepus', dutch: 'Hoest', category: 'Health' },
  { id: '489', latvian: 'Iesnas', dutch: 'Verkoudheid', category: 'Health' }, // Often used for runny nose/cold
  { id: '490', latvian: 'Galvassāpes', dutch: 'Hoofdpijn', category: 'Health' },
  { id: '491', latvian: 'Zobārsts', dutch: 'Tandarts', category: 'Health' },
  { id: '492', latvian: 'Asinis', dutch: 'Bloed', category: 'Health' },
  { id: '493', latvian: 'Sirds', dutch: 'Hart', category: 'Health' },
  { id: '494', latvian: 'Vēders', dutch: 'Maag', category: 'Health' },
  { id: '495', latvian: 'Mugura', dutch: 'Rug', category: 'Health' }, // Body part repetition but ok
  { id: '496', latvian: 'Alerģija', dutch: 'Allergie', category: 'Health' },
  { id: '497', latvian: 'Vakcīna', dutch: 'Vaccin', category: 'Health' },
  { id: '498', latvian: 'Vīruss', dutch: 'Virus', category: 'Health' },
  { id: '499', latvian: 'Palīdzība', dutch: 'Hulp', category: 'Health' },
  { id: '500', latvian: 'Dzīvība', dutch: 'Leven', category: 'Health' },
];

export const getBaseVocabulary = (): VocabularyItem[] => {
  // Returns a shallow copy - vocabulary items are read-only so this is safe
  return [...initialVocabulary];
};

export const getCategories = (): string[] => {
  const categories = new Set(initialVocabulary.map(item => item.category).filter(Boolean) as string[]);
  return Array.from(categories).sort();
};
